# Generated by Django 2.2.17 on 2020-11-18 19:58

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='Date in which this entity was created')),
                ('modified_datetime', models.DateTimeField(auto_now=True, help_text='Date in which this entity was modified the last time')),
                ('name', models.CharField(help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='name')),
                ('street_name', models.CharField(max_length=150)),
                ('street_number', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('province', models.CharField(blank=True, max_length=150)),
                ('country', models.CharField(blank=True, max_length=150)),
                ('postal_code', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RatingStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='Date in which this entity was created')),
                ('modified_datetime', models.DateTimeField(auto_now=True, help_text='Date in which this entity was modified the last time')),
                ('average_rating', models.FloatField(default=0)),
                ('number_five_star_ratings', models.IntegerField(default=0)),
                ('number_four_star_ratings', models.IntegerField(default=0)),
                ('number_three_star_ratings', models.IntegerField(default=0)),
                ('number_two_star_ratings', models.IntegerField(default=0)),
                ('number_one_star_ratings', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='Date in which this entity was created')),
                ('modified_datetime', models.DateTimeField(auto_now=True, help_text='Date in which this entity was modified the last time')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('message', models.CharField(blank=True, max_length=4000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='backend.Company')),
            ],
            options={
                'ordering': ['-created_datetime'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='rating_stats',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.RatingStats'),
        ),
    ]
